### ISSUE TITLE
Improve fake data feature to include support for Residencies feature

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#191]
We have recently changed our data model, adding a Residencies feature. The fake data generator does not generate Residencies data, so needs to be updated.

# Task
- [ ] Improve fake data feature to generate Residencies
- [ ] Residencies are created back to a date which is passed in via argument
- [ ] Optional: consider how to prevent residency overlap (i.e. a resident should only live in one house at a time)

**Comment by brylie** [comment]
Just spoke with @ErikPel, and they agreed to take this task.

**Comment by ErikPel** [comment]
Just wondering. Made script that added residency to all mock residents.

1. Should the script add multiple residencies to some of the residents so for example they lived at one place from january to june and another place for june till december? Or is it enough they have one residency?

**Comment by brylie** [comment]
Yes, multiple residencies for some percentage of residents would be helpful. Consider how the data generation functions might be parameteirzed, allowing, for example, one to specify the portion of residents to have multiple residencies. There are a few cases where residents move between houses, so this would more accurately model the system dynamics.

**Comment by ErikPel** [comment]
https://github.com/ErikPel/wellbeing/commit/a74a9c5adc45edd362c13b669914cc9e22a34e53
Heres the first draft, sorry for the messy commit. I hit auto format on my IDE 😢 

Here you set months from today as the starting point so for example if you use parameter 6 the residencies will start 6 months from now. The second parameters is the fraction of residents that will have move out date and then they are moved randomly into either moved out completely or moved into another home.
