### ISSUE TITLE
Improve performance of Home related views

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#196]
Currently, the Homes and Home Profile views are taking an abnormal time to render on deployments with more than 10,000 activity records. This seems to be due to missing collection indexes on fields used in important queries.

# Task
Improve Homes and Home Profile view performance by:

- [ ] adding index to Activities.residentIds field
- [ ] adding index to Activities.activityDate field
- [ ] changing `checkIfResidentWasActiveOnDate` method to use cursor count
