### ISSUE TITLE
Replace multi-select libraries with slim-select

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#237]
Currently, we have (at least) two multi-select libraries installed in this project -- neither of which are working 'perfectly'. The pending Bootstrap 3.x.x + jQuery 3.x upgrade is likely to cause further difficulties with the current multi-select libraries (based on struggles I've had in a different PR). So, to break through this barrier, it may be time to drop the other multi-select libraries and replace them with [slim-select](http://slimselectjs.com/).

# Task
- [ ] Remove bootstrap-select library/markup/javascript
- [ ] Remove select2
- [ ] Remove select2-bootstrap-theme
- [ ] Install slim-select library
- [ ] Replace Add Activity form Resident Select widget with slim-select
