### ISSUE TITLE
Upgrade/cleanup project dependencies

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#238]
As part of ongoing maintenance, we need to upgrade our dependencies. There are also a few duplicate or unused dependencies, which take up unnecessary space in our package. Upgrade and cleanup all dependencies.

# Task
- [ ] Remove redundant chart library dependencies
  - [x] dimple (Meteor package necessary)?
  - [ ] d3 (npm package only, if possible)
  - [x] nvd3 (npm package only, if possible)
  - [x] metrics graphics (npm package only, if possible)
- [x] simpl-schema - upgrade available
- [x] Meteor core, may have upgrade available
- [x]  upgrade all Meteor packages
- [x] remove any unused Meteor/npm packages
