### ISSUE TITLE
Remove unused charting libraries from project

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#242]
Now that most of the charts have been replaced, lets finish the task by removing the unused chart libraries.

## original issue
Currently, there are (at least) four active charting libraries used in this project:

- Dimple
- NVD3
- Metrics Graphics
- D3 (dependency)

### Task
- [x] Choose one versatile charting library (perhaps a new one altogether)
  - consider whether d3 should be a dependency
- [x] Replace as many charts with single library as possible
- [ ] Remove as many charting libraries as possible

**Comment by brylie** [comment]
I would particularly like to deprecate Dimple and NVD3, primarily because:

- they are not well maintained any longer
- they cannot easily be installed in the project via NPM
  - I have tried multiple times and had to resort to the Meteor module

I am considering installing plot.ly, but will compare available options.

The Metrics Graphics library seems nice, and may be included.

**Comment by brylie** [comment]
It is worth considering [C3.js](http://c3js.org/) to replace some of the charting libraries, such as NVD3. Alternatively, Plot.ly may be a good choice.

**Comment by brylie** [comment]
ping @marla-singer
