### ISSUE TITLE
Add Activity form not working when earliest available day is checking

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#245]
When testing the Add Activity form (at around 8PM EET) and selecting the first available day (i.e. seven days ago), the form would not submit. This is likely a validation error, and should indicate the error to the user. Additionally, the form should submit when any available day is selected, otherwise the day should not be available.

# Task
- [ ] Determine why the form would not submit
- [ ] Determine how to fix the issue so that the number of available days corresponds with valid form submission
- [ ] Adapt the schema, form, or whatever code is necessary to resolve the issue
