### ISSUE TITLE
Refactor individual resident page for reactive data updates

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#30]
The individual resident page currently renders charts only once, via the `Template.rendered` callback. As resident data may change dynamically while users are viewing the page, it may prove useful to allow reactive page updates. This pattern can be used throughout the application, including in the process of creating a reactive administrative dashboard.

# Task
Refactor all page elements on the individual resident page, so that they update reactively when server data is sent to the client. Specifically, the following page elements should refresh or re-render when model data changes:

* Activity trend chart (scatterplot with trend line)
* Activity calendar heatmap
* Activity table

# Criteria
* [x] Individual Resident page follows uni-directional dataflow approach
  * [x] 'smart-component' or parent template manages data subscription
  * [x] parent template passes data in to child templates via named data contexts
  * [x] child templates render data
  * [x] child templates reactively update when data model changes
* [x] Individual Resident template subscribes to all relevant data subsets for a given resident
  * [x] resident **details** (name, etc.)
  * [x] resident **activities**
* [ ] Sub-templates on the individual resident page re-render when the underlying data changes
  * [ ] activity trend chart
  * [ ] activity calendar heatmap
  * [ ] activity table

# Challenge
The page elements are rendered via non-reactive charting libraries, so need event handling logic to refresh when the data changes. This can be achieved via an `autorun()` block that triggers a refresh or re-render function on each template element when the model data changes.

**Comment by brylie** [comment]
@ErikPel, I am currently working on refactoring pages, so that charts are reactively updated when the data changes. Would this be an interesting starting point?

**Comment by brylie** [comment]
I have a working branch with much of the code in-place, but have not pushed it to Github. I can do so this evening.
