### ISSUE TITLE
Replace Home Profile Activity Summary by Type chart with Plotly.js

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#317]
On the Home Profile page, there is a chart called 'Activity Summary by Type':
![screenshot from 2019-01-27 11-22-16](https://user-images.githubusercontent.com/17307/51799132-48621580-2226-11e9-90bc-12654db5f5f4.png)

The chart is made with NVD3, which we are in the process of deprecating.

# Task
Replace the NVD3 version of the Home Profile Activity Summary by Type chart with Plotly.js. Make sure the functionality is mainly the same. Also, check for legend overlap on small screens, and fix if it happens.

- [ ] NVD3 chart is replaced with Plotly.js
- [ ] legend does not overlap chart on small screens
- [ ] interacting with legend allows chart to be filtered

BONUS: chart can be toggled to show *activity counts* or *activity minutes* (the data are already available).
