### ISSUE TITLE
Allow users to be assigned to groups

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#338]
After discussing with Marjo, we agreed that users should be assigned to groups. That means that a user will see all homes and residents that belong to that group.

# Task
- [x] data model supports user group assignment
- [x] Users can be assigned to group(s) from Users page
- only related homes/residents are visible to user when
  - [x] viewing Homes page
  - [x] viewing Home Profile
- Only relevant residents visible to user on:
  - [x] add activity form
- Only show correct residents on data entry forms
  - [x] Add Activity
  - [x] Add Feeling
- [x] Activities page should show only activities from user-visible residents
- [x] Home Report page should show 'Not Authorized' when user visits without proper group membership
- [x] Residents page should show only user-visible residents
- [x] Activities page filters Resident select should show only relevant homes and residents
- [x] Admin user should be able to see all homes, residents, and residencies
