### ISSUE TITLE
Create demo application deployment

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#512]
We need to demonstrate GeriLife for potential customers. Ideally, we would have a demo that we can deploy that would automatically create new data on a nightly basis (including resetting user accounts). A minimum requirement would be to be able to set up a demo with example data for one year so that we can showcase historical reporting.

## Task
- [ ] Determine the best way to approach being able to demo GeriLife
- [ ] Create deployment script/procedure/docker or whatever is relevant
- [ ] Demo should generate at least one year of data
- [ ] Care should be taken to prevent demo feature from being activated in actual deployments (some separation should be built-in)
- [ ] BONUS: Demo should showcase how users can be assigned to a group
