### ISSUE TITLE
Replace Plotly with eCharts

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#542]
Plotly is an excellent plotting library. However, the Apache eCharts library has a few compelling aspects:

- part of Apache Foundation
- many important chart types, incl. calendar heatmap
- declarative chart configuration

## Task
- [ ] Audit all chart types on our platform (incl. describing chart type and related view)
- [ ] Determine whether Apache ECharts supports each chart type
- [ ] Determine needed changes to data structures to support ECharts
- [ ] Discuss findings during a brief meeting to decide whether to make the transition

If it is agreed to make the transition from Plotly to ECharts:
- [ ] Replace all possible charts on our platform with equivalents from Apache eCharts.

**Comment by brylie** [comment]
This will be moved to the wellbeing-client project.
