### ISSUE TITLE
Add historic reporting for Home activity levels

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#543]
Now that our platform supports historical reporting, we can focus on improving the visibility of home activity levels over "deeper" periods.

We will start with historic charting for the individual homes before working on visualising the whole care-system.

## Task
- [ ] Design mock-ups for historic charts
- [ ] Describe types of aggregations needed for each chart mock-up (e.g. using `mode` or `mean` calculations for daily activity levels)
- [ ] Discuss required changes before implementing the improvements
- [ ] Add selected historical reports to Home report view

**Comment by shailee-m** [comment]
So we want to add 2 new charts:
1. calendar map (for the current year?): Based on count on activities on each day
2. Activities line chart: This is possibly the count or total time spend on activities.
How do we categorise the good bad and poor? In the code, there is the variable `yData` how do we calculate the three arrays.

The home activity and activity trend chart both can be viewed at following levels of time granularity:
1. year
2. month
3. week 
4. day

**Comment by shailee-m** [comment]
Also, I noticed this dense chart when there is a lot of data.

![image](https://user-images.githubusercontent.com/10625985/83904325-4b0b3e00-a77d-11ea-88e0-ea637f74d565.png)

We can remove the group mode. and only show stack-mode. Also, giving some dropdowns for filtering like for selecting a month or year, filtering by a home etc.

Few other reports can be helpful
1. Total activities in the past week (and list of top activities by time).
2. Most active homes this month/week whichever is more relevant.
3. Most active residents/homes (can be filtered by period of time month/year/week/day)

**Comment by shailee-m** [comment]
https://codepen.io/shailee-m/pen/LYGpWyJ

**Comment by brylie** [comment]
Looks good. I think the chart should be based on the following aggregation:

1. Calculate the percentage of active residents in each house for each day of the previous period (e.g. past 30 days)
2. Take the average (mean) of the daily active residents percentage for each house

The "average active residents level" can then be used to sort and compare houses of various sizes.

One nice addition would be to display the houses with the lowest average activity level, so managers can quickly identify areas for improvement.

**Comment by brylie** [comment]
Store the pre-computed "daily activity levels" percentages in the analytics cache for use in other charts such as the "activity level trends" chart on the Home view.

**Comment by shailee-m** [comment]
This average will "average active residents level" will be used to compare against the data from all the past months too?

**Comment by brylie** [comment]
Yes, it seems reasonable to compare averages across time as well as homes.

**Comment by shailee-m** [comment]
@brylie I was working on this card before the vue migration. I seem to have misunderstood this to be under the overall report page. But now that I revisited it I think it was for each home report page except for most active homes and least activity cards.

This is what I had created for the /report page.
![Screenshot from 2021-02-13 22-00-13](https://user-images.githubusercontent.com/10625985/107855338-9ebf4280-6e47-11eb-877d-ce5171e1866f.png)


Also, I was looking into the logic for heat map, which will basically be (active residents of all homes/total residents) of all homes for each day. It that correct?

**Comment by brylie** [comment]
> But now that I revisited it I think it was for each home report page except for most active homes and least activity cards.

Yes, this is the report page for a single Home.

> I was looking into the logic for heat map, which will basically be (active residents of all homes/total residents) of all homes for each day. It that correct?

Since this is the report page for a single Home, the heatmap should only show activity levels of residents who had an active residency at the Home for each calendar day.
