### ISSUE TITLE
Create mobile app build for iOS and Android

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#546]
We would like for GeriLife to be installed on user devices. To support this goal, let's leverage Cordova and produce both iOS and Android builds.

## Task
- [ ] Ensure client code and backend code are entirely separate
    - [ ] All client interactions with the server should happen via REST or method calls
- [ ] Add MIT license to client code, leave server code as AGPL
- [ ] Ensure most/all business logic is in server code. The client should only be responsible for rendering content
- [ ] Enable mobile client builds on the project.
    - [ ] iOS
    - [ ] Android
