### ISSUE TITLE
Add activity counts by facilitator role to Home historic report page

### ISSUE THREAD

**Issue by brylie** [GeriLife/wellbeing#588]
We currently have a dashboard to display historical data for a single home. However, the Home Report dashboard lacks some key charts, such as:

- activity counts by facilitator role

Note: the All Homes report can serve as the reference for this task, since it contains the desired data visualizations.

## Task scope

- [ ] server aggregation function exists
- [ ] server aggregation function uses indexed fields for performance
- [ ] server API endpoint exists
- [ ] Vue client code fetches aggregated data from a server API endpoint
- [ ] Vue client code displays aggregated data in appropriate chart and integrates well with other page elements

**Comment by shailee-m** [comment]
@brylie We already have an activity aggregation function so this task should take longer. It should be done in 2hours at most.

**Comment by brylie** [comment]
Yes, this is an end-to-end task. So, we would need server and client changes. I will add a task scope checklist for you to manage.
